# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7z100ffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.cache/wt [current_project]
set_property parent.project_path C:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/intel_project/AX7Z035/course_s1/13_PCIe_test_pl/PCIe_test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
add_files C:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/ip/design_1_util_ds_buf_0_1/design_1_util_ds_buf_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/ip/design_1_util_ds_buf_0_1/design_1_util_ds_buf_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0/user_design/constraints/design_1_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0/user_design/constraints/design_1_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/ip/design_1_rst_mig_7series_0_200M_0/design_1_rst_mig_7series_0_200M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/ip/design_1_rst_mig_7series_0_200M_0/design_1_rst_mig_7series_0_200M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/ip/design_1_rst_mig_7series_0_200M_0/design_1_rst_mig_7series_0_200M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1_0/design_1_proc_sys_reset_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1_0/design_1_proc_sys_reset_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1_0/design_1_proc_sys_reset_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_0/source/design_1_xdma_0_0_pcie2_ip-PCIE_X0Y0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_0/synth/design_1_xdma_0_0_pcie2_ip_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_1/xdma_v4_1_3_blk_mem_64_reg_be_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_2/xdma_v4_1_3_blk_mem_64_noreg_be_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_3/pcie2_fifo_generator_dma_cpl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_4/pcie2_fifo_generator_tgt_brdg.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_0/design_1_xdma_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_0/source/design_1_xdma_0_0_pcie3_7vx_ip.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_0/synth/design_1_xdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_1/design_1_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_1/design_1_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_1/design_1_auto_cc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_2/design_1_auto_cc_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_2/design_1_auto_cc_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_2/design_1_auto_cc_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/ip/design_1_s00_mmu_0_1/design_1_s00_mmu_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/ip/design_1_s01_mmu_0/design_1_s01_mmu_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/sources_1/bd/design_1/design_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/constrs_1/new/pcie.xdc
set_property used_in_implementation false [get_files C:/Users/Administrator/Desktop/Pcie/14_PCIe_test/PCIe_test.srcs/constrs_1/new/pcie.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top design_1_wrapper -part xc7z100ffg900-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
